// Add recursive getters
// Add enums
// Add methods
// Add constants
// Unrecognized fields
// Add toString, equals
// Add serialziers

import {
  type CodeGenerator,
  type Constant,
  type Doc,
  type Module,
  Record,
  type RecordKey,
  type RecordLocation,
} from "skir-internal";
import { z } from "zod";
import {
  getTypeName,
  getTypeRef,
  modulePathToCaselessEnumName,
  toStructFieldName,
} from "./naming.js";
import { TypeSpeller } from "./type_speller.js";

const Config = z.strictObject({});

type Config = z.infer<typeof Config>;

class SwiftCodeGenerator implements CodeGenerator<Config> {
  readonly id = "skir-swift-gen";
  readonly configType = Config;

  generateCode(input: CodeGenerator.Input<Config>): CodeGenerator.Output {
    const { recordMap, config } = input;
    const outputFile: CodeGenerator.OutputFile = {
      path: "skirout.swift",
      code: new SwiftSourceFileGenerator(
        input.modules,
        recordMap,
        config,
      ).generate(),
    };
    return { files: [outputFile] };
  }
}

/** Generates the code for the one .swift file. */
class SwiftSourceFileGenerator {
  constructor(
    private readonly skirModules: readonly Module[],
    recordMap: ReadonlyMap<RecordKey, RecordLocation>,
    private readonly config: Config,
  ) {
    this.typeSpeller = new TypeSpeller(recordMap);
  }

  generate(): string {
    // http://patorjk.com/software/taag/#f=Doom&t=Do%20not%20edit
    this.push(
      `//  ______                        _               _  _  _
      //  |  _  \\                      | |             | |(_)| |
      //  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
      //  | | | | / _ \\  | '_ \\  / _ \\ | __|  / _ \\ / _\` || || __|
      //  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_ 
      //  |___/   \\___/  |_| |_| \\___/  \\__|  \\___| \\__,_||_| \\__|
      //
      // Generated by skir-swift-gen
      // Home: https://github.com/gepheum/skir-swift-gen
      //
      // To install the Skir client library, run:
      //   ...

      import Foundation

      `,
    );

    for (const skirModule of this.skirModules) {
      const caselessEnumName = modulePathToCaselessEnumName(skirModule.path);
      this.push(`public enum ${caselessEnumName} {\n`);
      this.writeCodeForRecords(
        skirModule.declarations.filter((r) => r.kind === "record"),
      );
      this.push("}\n\n");
    }

    // if (this.inModule.methods.length) {
    //   this.pushSeparator("Methods");
    //   for (const method of this.inModule.methods) {
    //     this.writeMethod(method);
    //   }
    // }

    // if (this.inModule.constants.length) {
    //   this.pushSeparator("Constants");
    //   for (const constant of this.inModule.constants) {
    //     this.writeConstant(constant);
    //   }
    // }

    return this.joinLinesAndFixFormatting();
  }

  private writeCodeForRecords(records: readonly Record[]): void {
    for (const record of records) {
      if (record.recordType === "struct") {
        this.writeCodeForStruct(record);
      } else {
        this.writeCodeForEnum(record);
      }
    }
  }

  private writeCodeForStruct(struct: Record): void {
    const { typeSpeller } = this;
    const recordLocation = typeSpeller.recordMap.get(struct.key)!;
    const typeRef = getTypeRef(recordLocation, recordLocation);
    const typeName = getTypeName(struct);
    this.push(`public struct ${typeName} {\n`);
    for (const field of struct.fields) {
      const fieldName = toStructFieldName(field.name.text, field.isRecursive);
      const fieldType = typeSpeller.getSwiftType(
        field.type!,
        recordLocation,
        field.isRecursive,
      );
      this.push(
        commentify([
          docToCommentText(field.doc),
          ...(field.isRecursive === "hard"
            ? [
                "Recursive field. Boxed and optional to avoid infinite size.",
                "None should be treated the same as the default struct value.",
                `Use \`${fieldName}()\` to read this field without having to handle the Option,`,
                "but be careful not to call it from a recursive function as it may cause",
                "infinite recursion.",
              ]
            : []),
        ]),
      );
      this.push(`public let ${fieldName}: ${fieldType}\n`);
    }
    this.push("\n");
    this.push("public static let defaultValue = ", typeRef, "(\n");
    for (const field of struct.fields) {
      const fieldName = toStructFieldName(field.name.text, field.isRecursive);
      const defaultExpression = typeSpeller.getDefaultExpression(
        field.type!,
        recordLocation,
        field.isRecursive,
      );
      this.push(`${fieldName}: ${defaultExpression},\n`);
    }
    this.push(");\n\n");

    // Add getters for recursive fields.
    for (const field of struct.fields) {
      if (field.isRecursive !== "hard") continue;
      const getterName = toStructFieldName(field.name.text);
      const fieldName = toStructFieldName(field.name.text, field.isRecursive);
      const skirType = field.type!;
      const returnType = typeSpeller.getSwiftType(skirType, recordLocation);
      const defaultExpression = typeSpeller.getDefaultExpression(
        skirType,
        recordLocation,
      );
      this.push(`public func ${getterName}() -> ${returnType} {\n`);
      this.push(`return switch self.${fieldName} {\n`);
      this.push(`case .some(let rec): rec.value\n`);
      this.push(`case .none: ${defaultExpression}\n`);
      this.push("}\n");
      this.push("}\n\n");
    }

    // The partial() static factory method.
    this.push("public static func partial(\n");
    for (const field of struct.fields) {
      const fieldName = toStructFieldName(field.name.text, field.isRecursive);
      const fieldType = typeSpeller.getSwiftType(
        field.type!,
        recordLocation,
        field.isRecursive,
      );
      const defaultExpression = this.typeSpeller.getDefaultExpression(
        field.type!,
        recordLocation,
        field.isRecursive,
      );
      this.push(`${fieldName}: ${fieldType} = ${defaultExpression},\n`);
    }
    this.push(") -> ", typeRef, " {\n");
    this.push("return ", typeRef, "(\n");
    for (const field of struct.fields) {
      const fieldName = toStructFieldName(field.name.text, field.isRecursive);
      this.push(`${fieldName}: ${fieldName},\n`);
    }
    this.push(");\n");
    this.push("}\n\n");

    this.push("public func copy(\n");
    for (const field of struct.fields) {
      const fieldName = toStructFieldName(field.name.text, field.isRecursive);
      const fieldType = typeSpeller.getSwiftType(
        field.type!,
        recordLocation,
        field.isRecursive,
      );
      this.push(`${fieldName}: SkirClient.KeepOrSet<${fieldType}> = .keep,\n`);
    }
    this.push(") -> ", typeRef, " {\n");
    this.push("return ", typeRef, "(\n");
    for (const field of struct.fields) {
      const fieldName = toStructFieldName(field.name.text, field.isRecursive);
      this.push(`${fieldName}: {\n`);
      this.push(`switch ${fieldName} {\n`);
      this.push("case .keep:\n");
      this.push(`return self.${fieldName};\n`);
      this.push("case let .set(value):\n");
      this.push("return value;\n");
      this.push("}\n");
      this.push("}(),\n");
    }
    this.push(");\n");
    this.push("}\n\n");

    this.writeCodeForRecords(struct.nestedRecords);
    this.push("}\n\n");
  }

  private writeCodeForEnum(record: Record): void {
    const typeName = getTypeName(record);
    this.push(`public enum ${typeName} {\n`);
    this.push("case defaultValue;\n");
    this.push("\n");
    this.writeCodeForRecords(record.nestedRecords);
    this.push("}\n\n");
  }

  private push(...code: string[]): void {
    this.code += code.join("");
  }

  private joinLinesAndFixFormatting(): string {
    const indentUnit = "  ";
    let result = "";
    // The indent at every line is obtained by repeating indentUnit N times,
    // where N is the length of this array.
    const contextStack: Array<"{" | "(" | "[" | "<" | ":" | "."> = [];
    // Returns the last element in `contextStack`.
    const peakTop = (): string => contextStack.at(-1)!;
    const getMatchingLeftBracket = (r: "}" | ")" | "]" | ">"): string => {
      switch (r) {
        case "}":
          return "{";
        case ")":
          return "(";
        case "]":
          return "[";
        case ">":
          return "<";
      }
    };
    for (let line of this.code.split("\n")) {
      line = line.trim();
      if (line.length <= 0) {
        // Don't indent empty lines.
        result += "\n";
        continue;
      }

      const firstChar = line[0];
      switch (firstChar) {
        case "}":
        case ")":
        case "]":
        case ">": {
          const left = getMatchingLeftBracket(firstChar);
          while (contextStack.pop() !== left) {
            if (contextStack.length <= 0) {
              throw Error();
            }
          }
          break;
        }
        case ".": {
          if (peakTop() !== ".") {
            contextStack.push(".");
          }
          break;
        }
      }
      const indent =
        indentUnit.repeat(contextStack.length) +
        (line.startsWith("*") ? " " : "");
      result += `${indent}${line.trimEnd()}\n`;
      if (line.startsWith("/") || line.startsWith("*")) {
        // A comment.
        continue;
      }
      const lastChar = line.slice(-1);
      switch (lastChar) {
        case "{":
        case "(":
        case "[":
        case "<": {
          // The next line will be indented
          contextStack.push(lastChar);
          break;
        }
        case ":":
        case "=": {
          if (peakTop() !== ":") {
            contextStack.push(":");
          }
          break;
        }
        case ";":
        case ",": {
          if (peakTop() === "." || peakTop() === ":") {
            contextStack.pop();
          }
        }
      }
    }

    return (
      result
        // Remove spaces enclosed within curly brackets if that's all there is.
        .replace(/\{\s+\}/g, "{}")
        // Remove spaces enclosed within round brackets if that's all there is.
        .replace(/\(\s+\)/g, "()")
        // Remove spaces enclosed within square brackets if that's all there is.
        .replace(/\[\s+\]/g, "[]")
        // Remove empty line following an open curly bracket.
        .replace(/(\{\n *)\n/g, "$1")
        // Remove empty line preceding a closed curly bracket.
        .replace(/\n(\n *\})/g, "$1")
        // Coalesce consecutive empty lines.
        .replace(/\n\n\n+/g, "\n\n")
        .replace(/\n\n$/g, "\n")
    );
  }

  private readonly typeSpeller: TypeSpeller;
  private code = "";
}

function toSwiftStringLiteral(input: string): string {
  const escaped = input
    .replace(/\\/g, "\\\\") // Escape backslashes
    .replace(/"/g, '\\"') // Escape double quotes
    .replace(/\n/g, "\\n") // Escape newlines
    .replace(/\r/g, "\\r") // Escape carriage returns
    .replace(/\t/g, "\\t"); // Escape tabs
  return `"${escaped}"`;
}

function tryGetGoLiteral(constant: Constant): string | null {
  const type = constant.type!;
  if (type.kind !== "primitive") {
    return null;
  }
  const valueAsDenseJson = constant.valueAsDenseJson!;
  switch (type.primitive) {
    case "bool":
      return valueAsDenseJson ? "true" : "false";
    case "int32":
    case "int64":
    case "hash64":
    case "float32":
    case "float64": {
      const maybeQuoted = valueAsDenseJson.toString();
      if (
        maybeQuoted === "Infinity" ||
        maybeQuoted === "-Infinity" ||
        maybeQuoted === "NaN"
      ) {
        return null;
      } else {
        return maybeQuoted.startsWith('"') && maybeQuoted.endsWith('"')
          ? maybeQuoted.slice(1, -1)
          : maybeQuoted;
      }
    }
    case "string":
      return toSwiftStringLiteral(valueAsDenseJson as string);
  }
  return null;
}

function commentify(textOrLines: string | readonly string[]): string {
  const text = (
    typeof textOrLines === "string" ? textOrLines : textOrLines.join("\n")
  )
    .trim()
    .replace(/\n{3,}/g, "\n\n");
  if (text.length <= 0) {
    return "";
  }
  return text
    .split("\n")
    .map((line) => (line.length > 0 ? `/// ${line}\n` : `///\n`))
    .join("");
}

function docToCommentText(doc: Doc): string {
  return doc.pieces
    .map((p) => {
      switch (p.kind) {
        case "text":
          return p.text;
        case "reference":
          return "`" + p.referenceRange.text.slice(1, -1) + "`";
      }
    })
    .join("");
}

export const GENERATOR = new SwiftCodeGenerator();
