import Foundation

extension SkirClient {
    /// Protocol for type-erased per-variant behavior.
    fileprivate protocol VariantEntry<T> {
        associatedtype T
        func number() -> Int32
        func constant() -> T?
        func variantToJson(_ input: T, eolIndent: String?, out: inout String)
        func encodeValue(_ input: T, out: inout [UInt8])
        func wrapFromJson(_ json: Any, keepUnrecognized: Bool) throws -> T
        func wrapDecode(_ input: inout [UInt8], keepUnrecognized: Bool) throws -> T
    }

    /// Constant (non-wrapping) variant entry.
    fileprivate struct ConstantEntry<T: Clone>: VariantEntry {
        let variantNumber: Int32
        let variantName: String
        let instance: T

        func number() -> Int32 { variantNumber }
        func constant() -> T? { instance.cloned() }

        func variantToJson(_ input: T, eolIndent: String?, out: inout String) {
            if eolIndent != nil {
                writeJsonEscapedString(variantName, out: &out)
            } else {
                out.append(String(variantNumber))
            }
        }

        func encodeValue(_ input: T, out: inout [UInt8]) {
            encodeUInt32(UInt32(bitPattern: variantNumber), out: &out)
        }

        func wrapFromJson(_ json: Any, keepUnrecognized: Bool) throws -> T {
            throw DeserializeError.schema("variant '\(variantName)' is a constant, not a wrapper")
        }

        func wrapDecode(_ input: inout [UInt8], keepUnrecognized: Bool) throws -> T {
            throw DeserializeError.schema("variant '\(variantName)' is a constant, not a wrapper")
        }
    }

    /// Wrapper variant entry.
    fileprivate struct WrapperEntry<T, V>: VariantEntry {
        let variantNumber: Int32
        let variantName: String
        let serializer: Serializer<V>
        let wrap: (V) -> T
        let getValue: (T) -> V

        func number() -> Int32 { variantNumber }
        func constant() -> T? { nil }

        func variantToJson(_ input: T, eolIndent: String?, out: inout String) {
            let value = getValue(input)
            if let indent = eolIndent {
                let childIndent = indent + "  "
                out.append("{")
                out.append(childIndent)
                out.append("\"kind\": ")
                writeJsonEscapedString(variantName, out: &out)
                out.append(",")
                out.append(childIndent)
                out.append("\"value\": ")
                serializer._toJson(value, eolIndent: childIndent, out: &out)
                out.append(indent)
                out.append("}")
            } else {
                out.append("[")
                out.append(String(variantNumber))
                out.append(",")
                serializer._toJson(value, eolIndent: nil, out: &out)
                out.append("]")
            }
        }

        func encodeValue(_ input: T, out: inout [UInt8]) {
            serializer._encode(getValue(input), out: &out)
        }

        func wrapFromJson(_ json: Any, keepUnrecognized: Bool) throws -> T {
            let inner = try serializer._fromJson(json, keepUnrecognizedValues: keepUnrecognized)
            return wrap(inner)
        }

        func wrapDecode(_ input: inout [UInt8], keepUnrecognized: Bool) throws -> T {
            let inner = try serializer._decode(&input, keepUnrecognizedValues: keepUnrecognized)
            return wrap(inner)
        }
    }

    /// Main adapter for enum serialization/deserialization.
    /// For use only by code generated by the Skir code generator.
    public final class EnumAdapter<T: DefaultConstructible>: TypeAdapter {
        public typealias T = T

        private let getKindOrdinal: (T) -> Int
        private let wrapUnrecognized: (UnrecognizedVariantData<T>) -> T
        private let getUnrecognized: (T) -> UnrecognizedVariantData<T>?
        private var numberToEntry: [Int32: AnyEntry] = [:]
        private var removedNumbers: Set<Int32> = []
        private var nameToKindOrdinal: [String: Int] = [:]
        private var kindOrdinalToEntry: [AnyVariantEntry<T>?] = [nil]
        private var descVariants: [Reflection.EnumVariant] = []
        private let desc: Reflection.EnumDescriptor
        private let lock = NSLock()

        private enum AnyEntry {
            case removed
            case constant(Int)
            case wrapper(Int)
        }

        /// Creates a new `EnumAdapter`.
        public init(
            modulePath: String,
            qualifiedName: String,
            doc: String,
            getKindOrdinal: @escaping (T) -> Int,
            wrapUnrecognized: @escaping (UnrecognizedVariantData<T>) -> T,
            getUnrecognized: @escaping (T) -> UnrecognizedVariantData<T>?
        ) {
            self.getKindOrdinal = getKindOrdinal
            self.wrapUnrecognized = wrapUnrecognized
            self.getUnrecognized = getUnrecognized
            self.desc = Reflection.EnumDescriptor(
                modulePath: modulePath,
                qualifiedName: qualifiedName,
                doc: doc
            )
        }

        /// Registers a constant variant.
        public func addConstantVariant<V: Clone>(
            name: String,
            number: Int32,
            kindOrdinal: Int,
            doc: String,
            instance: V
        ) where V == T {
            lock.lock()
            defer { lock.unlock() }
            numberToEntry[number] = .constant(kindOrdinal)
            nameToKindOrdinal[name] = kindOrdinal
            let entry = ConstantEntry<T>(
                variantNumber: number,
                variantName: name,
                instance: instance
            )
            setKindOrdinalEntry(kindOrdinal, AnyVariantEntry(entry))
            descVariants.append(.constant(Reflection.EnumConstantVariant(name: name, number: number, doc: doc)))
        }

        /// Registers a wrapper variant.
        public func addWrapperVariant<V>(
            name: String,
            number: Int32,
            kindOrdinal: Int,
            serializer: Serializer<V>,
            doc: String,
            wrap: @escaping (V) -> T,
            getValue: @escaping (T) -> V
        ) {
            lock.lock()
            defer { lock.unlock() }
            numberToEntry[number] = .wrapper(kindOrdinal)
            nameToKindOrdinal[name] = kindOrdinal
            let entry = WrapperEntry<T, V>(
                variantNumber: number,
                variantName: name,
                serializer: serializer,
                wrap: wrap,
                getValue: getValue
            )
            setKindOrdinalEntry(kindOrdinal, AnyVariantEntry(entry))
            descVariants.append(.wrapper(Reflection.EnumWrapperVariant(
                name: name,
                number: number,
                variantType: serializer.typeDescriptor(),
                doc: doc
            )))
        }

        /// Registers a removed variant number.
        public func addRemovedNumber(_ number: Int32) {
            lock.lock()
            defer { lock.unlock() }
            numberToEntry[number] = .removed
            removedNumbers.insert(number)
        }

        /// Finalizes the adapter.
        public func finalize() {
            lock.lock()
            defer { lock.unlock() }
            descVariants.sort { $0.number < $1.number }
            desc.setVariants(descVariants)
            desc.setRemovedNumbers(removedNumbers)
        }

        /// Returns a reference to the pre-allocated descriptor.
        public func descriptor() -> Reflection.EnumDescriptor {
            desc
        }

        private func setKindOrdinalEntry(_ kindOrdinal: Int, _ entry: AnyVariantEntry<T>) {
            if kindOrdinal >= kindOrdinalToEntry.count {
                kindOrdinalToEntry.append(contentsOf: Array(repeating: nil as AnyVariantEntry<T>?, count: kindOrdinal + 1 - kindOrdinalToEntry.count))
            }
            kindOrdinalToEntry[kindOrdinal] = entry
        }

        // MARK: - TypeAdapter Implementation

        public func isDefault(_ input: T) -> Bool {
            getKindOrdinal(input) == 0
        }

        public func toJson(_ input: T, eolIndent: String?, out: inout String) {
            let ko = getKindOrdinal(input)
            if ko == 0 {
                unknownToJson(input, eolIndent: eolIndent, out: &out)
                return
            }
            if ko < kindOrdinalToEntry.count, let entry = kindOrdinalToEntry[ko] {
                entry.variantToJson(input, eolIndent: eolIndent, out: &out)
            } else {
                if eolIndent != nil {
                    out.append("\"UNKNOWN\"")
                } else {
                    out.append("0")
                }
            }
        }

        private func unknownToJson(_ input: T, eolIndent: String?, out: inout String) {
            if eolIndent != nil {
                out.append("\"UNKNOWN\"")
                return
            }
            if let u = getUnrecognized(input), !u.value.isEmpty {
                out.append(String(decoding: u.value, as: UTF8.self))
            } else {
                out.append("0")
            }
        }

        public func fromJson(_ json: Any, keepUnrecognizedValues: Bool) throws -> T {
            if let num = json as? NSNumber {
                if let i64 = num as? Int64 {
                    return resolveConstantLookup(Int32(i64), keepUnrecognized: keepUnrecognizedValues, rawJson: json)
                } else {
                    let i = num.intValue
                    return resolveConstantLookup(Int32(i), keepUnrecognized: keepUnrecognizedValues, rawJson: json)
                }
            }
            if let bool = json as? Bool {
                let num: Int32 = bool ? 1 : 0
                return resolveConstantLookup(num, keepUnrecognized: keepUnrecognizedValues, rawJson: json)
            }
            if let str = json as? String {
                if let ko = nameToKindOrdinal[str] {
                    if ko < kindOrdinalToEntry.count, let entry = kindOrdinalToEntry[ko] {
                        if let constant = entry.constant() {
                            return constant
                        } else {
                            throw DeserializeError.schema("variant '\(str)' is a wrapper, not a constant")
                        }
                    }
                }
                return T()
            }
            if let arr = json as? [Any], arr.count == 2 {
                let num = (arr[0] as? NSNumber)?.int32Value ?? 0
                switch numberToEntry[num] {
                case nil:
                    if keepUnrecognizedValues {
                        let bytes = try JSONSerialization.data(withJSONObject: json)
                        return wrapUnrecognized(UnrecognizedVariantData(number: num, value: Array(bytes)))
                    }
                    return T()
                case .removed:
                    return T()
                case .constant:
                    throw DeserializeError.schema("variant number \(num) is a constant, not a wrapper")
                case .wrapper(let ko):
                    if ko < kindOrdinalToEntry.count, let entry = kindOrdinalToEntry[ko] {
                        return try entry.wrapFromJson(arr[1], keepUnrecognized: keepUnrecognizedValues)
                    }
                    return T()
                }
            }
            if let obj = json as? [String: Any] {
                let name = (obj["kind"] as? String) ?? ""
                let valueJson = obj["value"] ?? NSNull()
                if let ko = nameToKindOrdinal[name] {
                    if ko < kindOrdinalToEntry.count, let entry = kindOrdinalToEntry[ko] {
                        if entry.constant() != nil {
                            throw DeserializeError.schema("variant '\(name)' is a constant, not a wrapper")
                        }
                        return try entry.wrapFromJson(valueJson, keepUnrecognized: keepUnrecognizedValues)
                    }
                }
                return T()
            }
            return T()
        }

        private func resolveConstantLookup(_ number: Int32, keepUnrecognized: Bool, rawJson: Any) -> T {
            switch numberToEntry[number] {
            case nil:
                if keepUnrecognized {
                    let bytes = (try? JSONSerialization.data(withJSONObject: rawJson)).map { Array($0) } ?? []
                    return wrapUnrecognized(UnrecognizedVariantData(number: number, value: bytes))
                }
                return T()
            case .removed:
                return T()
            case .wrapper:
                return T()
            case .constant(let ko):
                if ko < kindOrdinalToEntry.count, let entry = kindOrdinalToEntry[ko] {
                    return entry.constant() ?? T()
                }
                return T()
            }
        }

        public func encode(_ input: T, out: inout [UInt8]) {
            let ko = getKindOrdinal(input)
            if ko == 0 {
                encodeUInt32(0, out: &out)
                return
            }
            if ko < kindOrdinalToEntry.count, let entry = kindOrdinalToEntry[ko] {
                entry.encodeValue(input, out: &out)
            }
        }

        public func decode(_ input: inout [UInt8], keepUnrecognizedValues: Bool) throws -> T {
            let number = try decodeNumber(&input)
            guard number >= Int32.min, number <= Int32.max else {
                throw DeserializeError.schema("variant number out of range")
            }
            let num = Int32(number)
            switch numberToEntry[num] {
            case nil:
                if keepUnrecognizedValues {
                    let bytes = input
                    input.removeAll()
                    return wrapUnrecognized(UnrecognizedVariantData(number: num, value: bytes))
                }
                return T()
            case .removed:
                return T()
            case .constant(let ko):
                if ko < kindOrdinalToEntry.count, let entry = kindOrdinalToEntry[ko] {
                    return entry.constant() ?? T()
                }
                return T()
            case .wrapper(let ko):
                if ko < kindOrdinalToEntry.count, let entry = kindOrdinalToEntry[ko] {
                    return try entry.wrapDecode(&input, keepUnrecognized: keepUnrecognizedValues)
                }
                return T()
            }
        }

        public func typeDescriptor() -> Reflection.TypeDescriptor {
            .enumRecord(desc)
        }
    }
}

// MARK: - Helper Types

extension SkirClient {
    /// Type-erased variant entry for heterogeneous storage.
    fileprivate struct AnyVariantEntry<T> {
        private let _number: () -> Int32
        private let _constant: () -> T?
        private let _variantToJson: (T, String?, inout String) -> Void
        private let _encodeValue: (T, inout [UInt8]) -> Void
        private let _wrapFromJson: (Any, Bool) throws -> T
        private let _wrapDecode: (inout [UInt8], Bool) throws -> T

        init<Entry: VariantEntry>(_ entry: Entry) where Entry.T == T {
            self._number = { entry.number() }
            self._constant = { entry.constant() }
            self._variantToJson = { entry.variantToJson($0, eolIndent: $1, out: &$2) }
            self._encodeValue = { entry.encodeValue($0, out: &$1) }
            self._wrapFromJson = { try entry.wrapFromJson($0, keepUnrecognized: $1) }
            self._wrapDecode = { try entry.wrapDecode(&$0, keepUnrecognized: $1) }
        }

        func number() -> Int32 { _number() }
        func constant() -> T? { _constant() }
        func variantToJson(_ input: T, eolIndent: String?, out: inout String) {
            _variantToJson(input, eolIndent, &out)
        }
        func encodeValue(_ input: T, out: inout [UInt8]) {
            _encodeValue(input, &out)
        }
        func wrapFromJson(_ json: Any, keepUnrecognized: Bool) throws -> T {
            try _wrapFromJson(json, keepUnrecognized)
        }
        func wrapDecode(_ input: inout [UInt8], keepUnrecognized: Bool) throws -> T {
            try _wrapDecode(&input, keepUnrecognized)
        }
    }

    /// Protocol for types that can be cloned.
    public protocol Clone {
        func cloned() -> Self
    }
}

// Extend standard types to conform to Clone
extension Bool: SkirClient.Clone {
    public func cloned() -> Bool { self }
}

extension Int: SkirClient.Clone {
    public func cloned() -> Int { self }
}

extension Int32: SkirClient.Clone {
    public func cloned() -> Int32 { self }
}

extension Int64: SkirClient.Clone {
    public func cloned() -> Int64 { self }
}

extension String: SkirClient.Clone {
    public func cloned() -> String { self }
}
