import Foundation

extension SkirClient {
    /// Defines the item type, key type, and key extraction logic for a `KeyedArray`.
    ///
    /// Implementations of this protocol are generated by the Skir code generator.
    public protocol KeyedArraySpec {
        associatedtype Item
        associatedtype Key: Hashable

        /// Extracts the storage key from an item.
        static func getKey(from item: Item) -> Key
        /// Returns the dot-separated key path used in type descriptors.
        static func keyExtractor() -> String
        /// Returns the default item, used by `findByKeyOrDefault(_:)` when no matching element is found.
        static var defaultItem: Item { get }
    }

    /// An immutable array that supports O(1) lookup by key.
    ///
    /// The index is built lazily on the first call to `findByKey(_:)` and
    /// cached for subsequent calls. Building and caching the index is thread-safe.
    ///
    /// When multiple elements share the same key, `findByKey(_:)` returns the first one.
    public struct KeyedArray<Spec: SkirClient.KeyedArraySpec> {
        private final class IndexCache {
            var index: [Spec.Key: Int]?
            let lock = NSLock()
        }

        private let _items: [Spec.Item]
        private let _cache: IndexCache

        public init(_ items: [Spec.Item] = []) {
            _items = items
            _cache = IndexCache()
        }

        private var resolvedIndex: [Spec.Key: Int] {
            _cache.lock.lock()
            defer { _cache.lock.unlock() }
            if let existing = _cache.index {
                return existing
            }
            var map = [Spec.Key: Int](minimumCapacity: _items.count)
            for (i, item) in _items.enumerated() {
                let key = Spec.getKey(from: item)
                if map[key] == nil {
                    map[key] = i
                }
            }
            _cache.index = map
            return map
        }

        /// Returns the first element whose key equals `key`, or `nil`.
        ///
        /// The index is built on the first call and reused on all subsequent calls.
        public func findByKey(_ key: Spec.Key) -> Spec.Item? {
            guard let i = resolvedIndex[key] else { return nil }
            return _items[i]
        }

        /// Returns the first element whose key equals `key`, or `Spec.defaultItem`.
        ///
        /// The index is built on the first call and reused on all subsequent calls.
        public func findByKeyOrDefault(_ key: Spec.Key) -> Spec.Item {
            findByKey(key) ?? Spec.defaultItem
        }
    }
}

// MARK: - CustomStringConvertible

extension SkirClient.KeyedArray: CustomStringConvertible {
    public var description: String {
        _items.description
    }
}

// MARK: - RandomAccessCollection

extension SkirClient.KeyedArray: RandomAccessCollection {
    public typealias Index = Int
    public typealias Element = Spec.Item

    public var startIndex: Int { _items.startIndex }
    public var endIndex: Int { _items.endIndex }

    public subscript(position: Int) -> Spec.Item {
        _items[position]
    }
}

// MARK: - Equatable

extension SkirClient.KeyedArray: Equatable where Spec.Item: Equatable {
    public static func == (
        lhs: SkirClient.KeyedArray<Spec>,
        rhs: SkirClient.KeyedArray<Spec>
    ) -> Bool {
        lhs._items == rhs._items
    }
}

// MARK: - ExpressibleByArrayLiteral

extension SkirClient.KeyedArray: ExpressibleByArrayLiteral {
    public typealias ArrayLiteralElement = Spec.Item

    public init(arrayLiteral elements: Spec.Item...) {
        self.init(elements)
    }
}
