import Foundation

extension SkirClient {
    /// Protocol for type-erased per-field serialization behavior.
    fileprivate protocol FieldEntry<T> {
        associatedtype T
        func number() -> Int32
        func name() -> String
        func isFieldDefault(_ input: T) -> Bool
        func fieldToJson(_ input: T, eolIndent: String?, out: inout String)
        func fieldFromJson(_ json: Any, target: inout T, keepUnrecognized: Bool) throws
        func encodeField(_ input: T, out: inout [UInt8])
        func decodeField(_ input: inout [UInt8], target: inout T, keepUnrecognized: Bool) throws
    }

    /// Concrete field implementation storing metadata, adapter reference, and closures.
    fileprivate struct TypedField<T, V>: FieldEntry {
        let fieldNumber: Int32
        let fieldName: String
        let fieldDoc: String
        let serializer: Serializer<V>
        let getter: (T) -> V
        let setter: (inout T, V) -> Void

        func number() -> Int32 { fieldNumber }
        func name() -> String { fieldName }

        func isFieldDefault(_ input: T) -> Bool {
            serializer._isDefault(getter(input))
        }

        func fieldToJson(_ input: T, eolIndent: String?, out: inout String) {
            serializer._toJson(getter(input), eolIndent: eolIndent, out: &out)
        }

        func fieldFromJson(_ json: Any, target: inout T, keepUnrecognized: Bool) throws {
            let value = try serializer._fromJson(json, keepUnrecognizedValues: keepUnrecognized)
            setter(&target, value)
        }

        func encodeField(_ input: T, out: inout [UInt8]) {
            serializer._encode(getter(input), out: &out)
        }

        func decodeField(_ input: inout [UInt8], target: inout T, keepUnrecognized: Bool) throws {
            let value = try serializer._decode(&input, keepUnrecognizedValues: keepUnrecognized)
            setter(&target, value)
        }
    }

    /// Main adapter for struct serialization/deserialization.
    /// For use only by code generated by the Skir code generator.
    public final class StructAdapter<T: DefaultConstructible>: TypeAdapter {
        public typealias T = T

        private let getUnrecognized: (T) -> UnrecognizedFieldsData<T>?
        private let setUnrecognized: (inout T, UnrecognizedFieldsData<T>?) -> Void
        private var orderedEntries: [AnyFieldEntry<T>] = []
        private var nameToIndex: [String: Int] = [:]
        private var slotToIndex: [Int?] = []
        private var removedNumbers: Set<Int32> = []
        private let desc: Reflection.StructDescriptor
        private let lock = NSLock()
        private var finalized = false

        /// Creates a new `StructAdapter`.
        public init(
            modulePath: String,
            qualifiedName: String,
            doc: String,
            getUnrecognized: @escaping (T) -> UnrecognizedFieldsData<T>?,
            setUnrecognized: @escaping (inout T, UnrecognizedFieldsData<T>?) -> Void
        ) {
            self.getUnrecognized = getUnrecognized
            self.setUnrecognized = setUnrecognized
            self.desc = Reflection.StructDescriptor(
                modulePath: modulePath,
                qualifiedName: qualifiedName,
                doc: doc
            )
        }

        /// Registers a field with getter/setter closures.
        public func addField<V>(
            _ name: String,
            number: Int32,
            serializer: Serializer<V>,
            getter: @escaping (T) -> V,
            setter: @escaping (inout T, V) -> Void,
            doc: String
        ) {
            lock.lock()
            defer { lock.unlock() }
            let field = TypedField<T, V>(
                fieldNumber: number,
                fieldName: name,
                fieldDoc: doc,
                serializer: serializer,
                getter: getter,
                setter: setter
            )
            let entry: AnyFieldEntry<T> = AnyFieldEntry(field)
            nameToIndex[name] = orderedEntries.count
            orderedEntries.append(entry)
        }

        /// Registers a field number that was removed from the schema.
        public func addRemovedNumber(_ number: Int32) {
            lock.lock()
            defer { lock.unlock() }
            removedNumbers.insert(number)
        }

        /// Finalizes the adapter, building lookup tables.
        public func finalize() {
            lock.lock()
            defer { lock.unlock() }
            orderedEntries.sort { $0.number() < $1.number() }
            nameToIndex.removeAll(keepingCapacity: true)
            for (index, entry) in orderedEntries.enumerated() {
                nameToIndex[entry.name()] = index
            }
            let maxNumber = orderedEntries.map { Int($0.number()) }.max() ?? -1
            slotToIndex = Array(repeating: nil, count: maxNumber + 1)
            for (index, entry) in orderedEntries.enumerated() {
                slotToIndex[Int(entry.number())] = index
            }
            desc.setFields(orderedEntries.map { entry in
                Reflection.StructField(
                    name: entry.name(),
                    number: entry.number(),
                    fieldType: .primitive(.string),
                    doc: ""
                )
            })
            desc.setRemovedNumbers(removedNumbers)
            finalized = true
        }

        /// Returns a reference to the pre-allocated descriptor.
        public func descriptor() -> Reflection.StructDescriptor {
            desc
        }

        // MARK: - TypeAdapter Implementation

        public func isDefault(_ input: T) -> Bool {
            if getUnrecognized(input) != nil {
                return false
            }
            return orderedEntries.allSatisfy { $0.isFieldDefault(input) }
        }

        public func toJson(_ input: T, eolIndent: String?, out: inout String) {
            if let indent = eolIndent {
                toReadableJson(input, indent: indent, out: &out)
            } else {
                toDenseJson(input, out: &out)
            }
        }

        private func toDenseJson(_ input: T, out: inout String) {
            out.append("[")
            let slotCount = getSlotCount(input)
            for i in 0 ..< slotCount {
                if i > 0 {
                    out.append(",")
                }
                if i < slotToIndex.count, let idx = slotToIndex[i] {
                    orderedEntries[idx].fieldToJson(input, eolIndent: nil, out: &out)
                } else {
                    out.append("0")
                }
            }
            out.append("]")
        }

        private func toReadableJson(_ input: T, indent: String, out: inout String) {
            out.append("{")
            let childIndent = indent + "  "
            var first = true
            for entry in orderedEntries {
                if entry.isFieldDefault(input) {
                    continue
                }
                if !first {
                    out.append(",")
                }
                first = false
                out.append(childIndent)
                SkirClient.writeJsonEscapedString(entry.name(), out: &out)
                out.append(": ")
                entry.fieldToJson(input, eolIndent: childIndent, out: &out)
            }
            if !first {
                out.append(indent)
            }
            out.append("}")
        }

        private func getSlotCount(_ input: T) -> Int {
            for entry in orderedEntries.reversed() {
                if !entry.isFieldDefault(input) {
                    return Int(entry.number()) + 1
                }
            }
            return 0
        }

        public func fromJson(_ json: Any, keepUnrecognizedValues: Bool) throws -> T {
            var t = T()
            if let arr = json as? [Any] {
                try fromDenseJson(arr, target: &t, keepUnrecognized: keepUnrecognizedValues)
            } else if let obj = json as? [String: Any] {
                try fromReadableJson(obj, target: &t, keepUnrecognized: keepUnrecognizedValues)
            }
            return t
        }

        private func fromDenseJson(_ arr: [Any], target: inout T, keepUnrecognized: Bool) throws {
            for entry in orderedEntries {
                let n = Int(entry.number())
                if n >= arr.count {
                    break
                }
                try entry.fieldFromJson(arr[n], target: &target, keepUnrecognized: keepUnrecognized)
            }
        }

        private func fromReadableJson(_ obj: [String: Any], target: inout T, keepUnrecognized: Bool) throws {
            for (key, val) in obj {
                if let idx = nameToIndex[key] {
                    try orderedEntries[idx].fieldFromJson(val, target: &target, keepUnrecognized: keepUnrecognized)
                }
            }
        }

        public func encode(_ input: T, out: inout [UInt8]) {
            let slotCount = getSlotCount(input)
            if slotCount <= 3 {
                out.append(246 + UInt8(slotCount))
            } else {
                out.append(250)
                encodeUInt32(UInt32(slotCount), out: &out)
            }
            for i in 0 ..< slotCount {
                if i < slotToIndex.count, let idx = slotToIndex[i] {
                    orderedEntries[idx].encodeField(input, out: &out)
                } else {
                    out.append(0)
                }
            }
        }

        public func decode(_ input: inout [UInt8], keepUnrecognizedValues: Bool) throws -> T {
            var t = T()
            let wire = try SkirClient.readU8(&input)
            if wire == 0 || wire == 246 {
                return t
            }
            let slotCount: Int
            if wire == 250 {
                let decoded = try SkirClient.decodeNumber(&input)
                guard decoded >= 0 else {
                    throw DeserializeError.schema("unexpected negative struct slot count")
                }
                slotCount = Int(decoded)
            } else {
                slotCount = Int(wire) - 246
            }
            let recognizedCount = slotToIndex.count
            let slotsToFill = min(slotCount, recognizedCount)
            for i in 0 ..< slotsToFill {
                if let idx = slotToIndex[i] {
                    try orderedEntries[idx].decodeField(&input, target: &t, keepUnrecognized: keepUnrecognizedValues)
                } else {
                    try SkirClient.skipValue(&input)
                }
            }
            if slotCount > recognizedCount {
                for _ in recognizedCount ..< slotCount {
                    try SkirClient.skipValue(&input)
                }
            }
            return t
        }

        public func typeDescriptor() -> Reflection.TypeDescriptor {
            .structRecord(desc)
        }
    }
}

// MARK: - Helper Types

extension SkirClient {
    /// Type-erased field entry for heterogeneous storage.
    fileprivate struct AnyFieldEntry<T> {
        private let _number: () -> Int32
        private let _name: () -> String
        private let _isFieldDefault: (T) -> Bool
        private let _fieldToJson: (T, String?, inout String) -> Void
        private let _fieldFromJson: (Any, inout T, Bool) throws -> Void
        private let _encodeField: (T, inout [UInt8]) -> Void
        private let _decodeField: (inout [UInt8], inout T, Bool) throws -> Void

        init<Entry: FieldEntry>(_ entry: Entry) where Entry.T == T {
            self._number = { entry.number() }
            self._name = { entry.name() }
            self._isFieldDefault = { entry.isFieldDefault($0) }
            self._fieldToJson = { entry.fieldToJson($0, eolIndent: $1, out: &$2) }
            self._fieldFromJson = { try entry.fieldFromJson($0, target: &$1, keepUnrecognized: $2) }
            self._encodeField = { entry.encodeField($0, out: &$1) }
            self._decodeField = { try entry.decodeField(&$0, target: &$1, keepUnrecognized: $2) }
        }

        func number() -> Int32 { _number() }
        func name() -> String { _name() }
        func isFieldDefault(_ input: T) -> Bool { _isFieldDefault(input) }
        func fieldToJson(_ input: T, eolIndent: String?, out: inout String) {
            _fieldToJson(input, eolIndent, &out)
        }
        func fieldFromJson(_ json: Any, target: inout T, keepUnrecognized: Bool) throws {
            try _fieldFromJson(json, &target, keepUnrecognized)
        }
        func encodeField(_ input: T, out: inout [UInt8]) {
            _encodeField(input, &out)
        }
        func decodeField(_ input: inout [UInt8], target: inout T, keepUnrecognized: Bool) throws {
            try _decodeField(&input, &target, keepUnrecognized)
        }
    }

    /// Protocol for types that can be default-constructed.
    public protocol DefaultConstructible {
        init()
    }
}
